[client]
handle = "Dein Name"              # Benutzername im Chat
port = 5000                       # Portbereich, auf dem der Client Nachrichten empfängt
whoisport = 4000                  # Port für Broadcasts vom Discovery-Dienst
autoreply = "Ich bin gerade nicht da."  # Automatische Antwort im Abwesenheitsmodus
imagepath = "images/" 

[network]
whoisport = 4000 ##für Discovery-Dienst
port_min = 5000
port_max = 5010