autoreply = "bin nicht da"

[client]
handle = "Busra"
port = 5000
whoisport = 4000
autoreply = "Bin arbeiten."
imagepath = "images/"

[network]
whoisdiscoveryport = 4000
port_min = 5000
port_max = 5010
