[client]
handle = "büsra"              # Benutzername im Chat
port = 5000                       # Portbereich, auf dem der Client Nachrichten empfängt
whoisport = 4000                  # Port für Broadcasts vom Discovery-Dienst
autoreply = "Bin arbeiten."  # Automatische Antwort im Abwesenheitsmodus
autoreply_aktiv = true
imagepath = "images/" 
[network]
bildport = 7000
whoisdiscoveryport = 4000
port_min = 5000
port_max = 5010