[client]
handle = "Jana"
port = 5000
whoisport = 4000
autoreply = "Bin nicht mehr da"
autoreply_aktiv = true
imagepath = "images/"

[network]
whoisdiscoveryport = 4000
port_min = 5000
port_max = 5300
